resources:
  basedosdados_config:
    config:
      table_id: ""
      dataset_id: ""
  timezone_config:
    config:
      timezone: "America/Sao_Paulo"
  discord_webhook:
    config:
      url: "{{ '' | env_override('BRT_DISCORD_WEBHOOK') }}"
      success_cron: "* * * * *"
solids:
  get_runs:
    inputs:
      execution_date:
        value: ""
