version: "3.3"

services:
  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - 6379:6379

  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
