# Dagster libraries to run both dagit and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.8-slim

COPY requirements.txt .
RUN pip install -r requirements.txt

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY .dagster_workspace/dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

RUN apt-get update && apt-get install -y procps
