schedules:
- module: repositories.capturas.schedules
  objects:
  - br_rj_riodejaneiro_brt_gps_registros
  - br_rj_riodejaneiro_onibus_gps_registros
pipelines:
- module: repositories.capturas.br_rj_riodejaneiro_brt_gps.registros
  objects:
  - br_rj_riodejaneiro_brt_gps_registros
  - br_rj_riodejaneiro_brt_gps_registros_init
- module: repositories.capturas.br_rj_riodejaneiro_onibus_gps.registros
  objects:
  - br_rj_riodejaneiro_onibus_gps_registros
  - br_rj_riodejaneiro_onibus_gps_registros_init
- module: repositories.capturas.br_rj_riodejaneiro_brt_rdo.registros
  objects:
  - br_rj_riodejaneiro_brt_rdo_registros
  - br_rj_riodejaneiro_brt_rdo_registros_init
- module: repositories.capturas.br_rj_riodejaneiro_onibus_rdo.registros
  objects:
  - br_rj_riodejaneiro_onibus_rdo_registros
  - br_rj_riodejaneiro_onibus_rdo_registros_init