{{ range $deployment := .Values.deployments }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}
  labels:
    {{- include "dagster.labels" $ | nindent 4 }}
    component: user-deployments
    deployment: {{ $deployment.name }}
  annotations:
    {{- if hasKey $deployment "service" }}
    {{- if hasKey $deployment.service "annotations" }}
    {{- range $key, $value := $deployment.service.annotations }}
    {{ $key }}: {{ $value | squote }}
    {{- end }}
    {{- end }}
    {{- end }}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ $deployment.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "dagster.selectorLabels" $ | nindent 4 }}
    component: user-deployments
    deployment: {{ $deployment.name }}
---
{{ end }}
