---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: citus-master
  name: citus-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
