name: Build, publish and deploy

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main, feature/k8s]
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: us-central1-c
  IMAGE: maestro-user-code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker with gcloud
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Build Docker image
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            .

      - name: Publish Docker image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      - name: Update image repository on values.yaml for dagster-user-deployments
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: "gke/dagster-user-deployments-values.yaml"
          propertyPath: "deployments.0.image.repository"
          value: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}
          commitChange: false
          updateFile: true

      - name: Update image tag on values.yaml for dagster-user-deployments
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: "gke/dagster-user-deployments-values.yaml"
          propertyPath: "deployments.0.image.tag"
          value: ${{ env.GITHUB_SHA }}
          commitChange: false
          updateFile: true

      - name: Deploy
        run: |-
          helm upgrade --install user-code ./helm/dagster-user-deployments/ -f gke/dagster-user-deployments-values.yaml -n dagster
          kubectl get services -n dagster -o wide
